version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./nawy-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/apartment-listings"
      NODE_ENV: "development"
    volumes:
      - ./nawy-backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./nawy-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./nawy-frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: "development"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: